databases:
  - name: sampleapp-db
    databaseName: sampleapp-db
    user: wordtest
    region: singapore

services:
  - type: web
    name: wordtest
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sampleapp-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

